---
title: "BARD 2018"
author: "Andrew Iraola"
date: "12/23/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(tidytext)
library(wordcloud)
library(RColorBrewer)
library(wordcloud2)
library(tm)
```

```{r}
library(readxl)
ReleasableAccidents2018 <- read_excel("ReleasableAccidents2018.xlsx")

BARD <- ReleasableAccidents2018

Narrative <- BARD %>%
  select(RedactedNarrative)
```

```{r}
docs <- Corpus(VectorSource(Narrative))
inspect(docs)
```


```{r}
toSpace <- content_transformer(function (x , pattern ) gsub(pattern, " ", x))
docs <- tm_map(docs, toSpace, "/")
docs <- tm_map(docs, toSpace, "@")
docs <- tm_map(docs, toSpace, "\\|")
```

```{r}
# Convert the text to lower case
docs <- tm_map(docs, content_transformer(tolower))
# Remove numbers
docs <- tm_map(docs, removeNumbers)
# Remove english common stopwords
#docs <- tm_map(docs, removeWords, stopwords("english"))
# Remove your own stop word
# specify your stopwords as a character vector
docs <- tm_map(docs, removeWords, c("and", "the", "was")) 

docs <- tm_map(docs, removeWords, c("operator", "vessel"))

docs <- tm_map(docs, removeWords, c("area", "with", "were", "that", "had", "they", "from", "stated",
                                    "this", "there", "time", "him", "her", "for", "while", "after",
                                    "said", "when", "but", "two", "did", "into", "other", "then"))

docs <- tm_map(docs, removeWords, c("he", "she", "his", "not"))
# Remove punctuations
docs <- tm_map(docs, removePunctuation)
# Eliminate extra white spaces
docs <- tm_map(docs, stripWhitespace)
# Text stemming
# docs <- tm_map(docs, stemDocument)
```


```{r}
dtm <- TermDocumentMatrix(docs)
m <- as.matrix(dtm)
v <- sort(rowSums(m),decreasing=TRUE)
d <- data.frame(word = names(v),freq=v)
head(d, 10)
```

```{r}
set.seed(1234)
wordcloud(words = d$word, freq = d$freq, min.freq = 1,
          max.words=60, random.order=FALSE, rot.per=0.35, 
          colors=brewer.pal(8, "Dark2"))
```
```{r}
findFreqTerms(dtm, lowfreq = 2000)
```
```{r}
barplot(d[1:10,]$freq, las = 2, names.arg = d[1:10,]$word,
        col ="lightblue", main ="Most frequent words",
        ylab = "Word frequencies")
```
