---
title: "Propeller Injury Trend Analysis"
author: "Andrew Iraola"
date: "6/4/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Propeller Deaths by State (2015-2019)
We're going to look at the past five years of data for this analysis. All data sourced from BARD database tables, 2015-2019. Specifically, the "Deceased Table". 

```{r, echo=FALSE, message=FALSE}
library(readxl)
library(ggplot2)
library(dplyr)

Injured_Trend <- read_excel("Propeller Injury Query_2015-19.xlsx", sheet = 6)

Injured_2015 <- read_excel("Propeller Injury Query_2015-19.xlsx", sheet = 5)

Injured_2016 <- read_excel("Propeller Injury Query_2015-19.xlsx", sheet = 4)

Injured_2017 <- read_excel("Propeller Injury Query_2015-19.xlsx", sheet = 3)

Injured_2018 <- read_excel("Propeller Injury Query_2015-19.xlsx", sheet = 2)

Injured_2019 <- read_excel("Propeller Injury Query_2015-19.xlsx", sheet = 1)
```

```{r}
df_PropellerInjury_2015 <- Injured_2015 %>%
  group_by(PropellerInjury, State) %>%
  filter(State!="NA") %>%
  filter(PropellerInjury=="Y") %>%
  summarise(counts = n()) %>%
  filter(counts>=3)


InjuryPlot_2015 <- ggplot(df_PropellerInjury_2015, aes(x = State, y = counts)) +
  geom_bar(fill = "#0073C2FF", stat = "identity") +
  geom_text(aes(label = counts), vjust = 0) + 
 labs(y = "Total Injuries", fill="test", x = "") +
  scale_y_continuous(limits = c(0, 22), breaks = c(0,2,4,6,8,10,12,14,16,18, 20, 22)) + theme_minimal()  + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) 

InjuryPlot_2015
```

```{r}
df_PropellerInjury_2016 <- Injured_2016 %>%
  group_by(PropellerInjury, State) %>%
  filter(State!="NA") %>%
  filter(PropellerInjury=="Y") %>%
  summarise(counts = n()) %>%
  filter(counts>=3)


InjuryPlot_2016<- ggplot(df_PropellerInjury_2016, aes(x = State, y = counts)) +
  geom_bar(fill = "#0073C2FF", stat = "identity") +
  geom_text(aes(label = counts), vjust = 0) + 
 labs(y = "", fill="test", x = "") +
  scale_y_continuous(limits = c(0, 22), breaks = c(0,2,4,6,8,10,12,14,16,18, 20, 22)) + theme_minimal()  + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) 

InjuryPlot_2016
```


```{r}
df_PropellerInjury_2017 <- Injured_2017 %>%
  group_by(InjuredPropellerInjury, InjuredState) %>%
  filter(InjuredState!="NA") %>%
  filter(InjuredPropellerInjury=="Y") %>%
  summarise(counts = n()) %>%
  filter(counts>=3)


InjuryPlot_2017<- ggplot(df_PropellerInjury_2017, aes(x = InjuredState, y = counts)) +
  geom_bar(fill = "#0073C2FF", stat = "identity") +
  geom_text(aes(label = counts), vjust = 0) + 
 labs(y = "", fill="test", x = "") +
  scale_y_continuous(limits = c(0, 22), breaks = c(0,2,4,6,8,10,12,14,16,18, 20, 22)) + theme_minimal()  + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) 

InjuryPlot_2017
```



```{r}
df_PropellerInjury_2018 <- Injured_2018 %>%
  group_by(InjuredPropellerInjury, InjuredState) %>%
  filter(InjuredState!="NA") %>%
  filter(InjuredPropellerInjury=="Y") %>%
  summarise(counts = n()) %>%
  filter(counts>=3)


InjuryPlot_2018 <- ggplot(df_PropellerInjury_2018, aes(x = InjuredState, y = counts)) +
  geom_bar(fill = "#0073C2FF", stat = "identity") +
  geom_text(aes(label = counts), vjust = 0) + 
 labs(y = "Total Injuries", fill="test", x = "", caption  = "Figures highlight states with three or more injuries per year" )+
  scale_y_continuous(limits = c(0, 22), breaks = c(0,2,4,6,8,10,12,14,16,18, 20, 22)) + theme_minimal()  + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  theme(plot.caption = element_text(hjust = 0, face= "italic")) +
  theme(plot.subtitle = element_text(hjust= -3))

InjuryPlot_2018
```

```{r}
df_PropellerInjury_2019 <- Injured_2019 %>%
  group_by(InjuredPropellerInjury, InjuredState) %>%
  filter(InjuredState!="NA") %>%
  filter(InjuredPropellerInjury=="Y") %>%
  summarise(counts = n()) %>%
  filter(counts>=3)


InjuryPlot_2019 <- ggplot(df_PropellerInjury_2019, aes(x = InjuredState, y = counts)) +
  geom_bar(fill = "#0073C2FF", stat = "identity") +
  geom_text(aes(label = counts), vjust = 0) + 
 labs(y = "", fill="test", x = "") +
  scale_y_continuous(limits = c(0, 22), breaks = c(0,2,4,6,8,10,12,14,16,18, 20, 22)) + theme_minimal()  + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) 

InjuryPlot_2019
```


```{r}
library("cowplot")
plot_row_injuries <- plot_grid(InjuryPlot_2015, InjuryPlot_2016, InjuryPlot_2017, InjuryPlot_2018, InjuryPlot_2019,
          labels = c("2015", "2016", "2017", "2018", "2019"), hjust = -5.5,
          ncol = 3, nrow = 2)

title_injuries <- ggdraw() + 
  draw_label(
    "Number of Injuries Associated with Propellers by State (2015-2019)",
    fontface = 'bold',
    x = 0,
    hjust = 0
  ) +
  theme(
    # add margin on the left of the drawing canvas,
    # so title is aligned with left edge of first plot
    plot.margin = margin(0, 0, 0, 7)
  )

Final_Plot_Injuries <- plot_grid(
  title_injuries, plot_row_injuries,
  ncol = 1,
  # rel_heights values control vertical title margins
  rel_heights = c(0.1, 1)
)

Final_Plot_Injuries
```


```{r}
df_PropellerFatality_Trend <- Injured_Trend %>%
  group_by(PropellerInjury, State) %>%
  filter(PropellerInjury=="Y") %>%
  filter(State!="NA") %>%
  summarise(counts = n()) %>%
  filter(counts>=10)

InjuryPlot_Trend <- ggplot(df_PropellerFatality_Trend, aes(x = State, y = counts)) +
  geom_bar(aes(reorder(State, counts), counts), fill = "#0073C2FF", stat = "identity") +
  geom_text(aes(label = counts), vjust = -0.3)  +
  scale_y_continuous(limits = c(0, 100), breaks = c(0,10, 20, 30, 40, 50, 60, 70, 80, 90, 100)) +
labs(y = "Total Injuries", fill="test", x = "State (Acronym)", title = "Number of Injuries Associated with a Propeller by State (2015-2019)", subtitle="Figure highlights states with 10 or more injuries over the past five years") + theme_minimal() + 
  theme(axis.text.x = element_text(angle = 50, hjust = 1))

InjuryPlot_Trend


```

```{r}
df_PropellerInjury_2015 <- Injured_2015 %>%
  group_by(PropellerInjury, TypeOfBodyOfWater) %>%
  filter(PropellerInjury=="Y") %>%
  summarise(counts = n()) %>%
  filter(counts>=3)


Injuries_BodyofWater_2015 <- ggplot(df_PropellerInjury_2015, aes(x = TypeOfBodyOfWater, y = counts)) +
  geom_bar(fill = "#0073C2FF", stat = "identity") +
  geom_text(aes(label = counts), vjust = -0.3) + 
 labs(y = "Total Injuries", fill="test", x = "") +
  scale_y_continuous(limits = c(0, 100), breaks = c(0, 20, 40, 60, 80, 100)) + 
  theme(axis.text.x = element_text(angle = 50, hjust = 1)) + theme_minimal()

Injuries_BodyofWater_2015
```

```{r}
df_PropellerInjury_2016 <- Injured_2016 %>%
  group_by(PropellerInjury, TypeOfBodyOfWater) %>%
  filter(PropellerInjury=="Y") %>%
  summarise(counts = n()) %>%
  filter(counts>=3)


Injuries_BodyofWater_2016 <- ggplot(df_PropellerInjury_2016, aes(x = TypeOfBodyOfWater, y = counts)) +
  geom_bar(fill = "#0073C2FF", stat = "identity") +
  geom_text(aes(label = counts), vjust = -0.3) + 
 labs(y = "", fill="test", x = "") +
  scale_y_continuous(limits = c(0, 100), breaks = c(0, 20, 40, 60, 80, 100)) + 
  theme(axis.text.x = element_text(angle = 50, hjust = 1)) + theme_minimal()

Injuries_BodyofWater_2016
```

```{r}
df_PropellerInjury_2017 <- Injured_2017 %>%
  group_by(InjuredPropellerInjury, BoWCat) %>%
  filter(InjuredPropellerInjury=="Y") %>%
  summarise(counts = n()) %>%
  filter(counts>=3)


Injuries_BodyofWater_2017 <- ggplot(df_PropellerInjury_2017, aes(x = BoWCat, y = counts)) +
  geom_bar(fill = "#0073C2FF", stat = "identity") +
  geom_text(aes(label = counts), vjust = -0.3) + 
 labs(y = "", fill="test", x = "") +
  scale_y_continuous(limits = c(0, 100), breaks = c(0, 20, 40, 60, 80, 100)) + 
  theme(axis.text.x = element_text(angle = 50, hjust = 1)) + theme_minimal()

Injuries_BodyofWater_2017
```

```{r}
df_PropellerInjury_2018 <- Injured_2018 %>%
  group_by(InjuredPropellerInjury, TypeOfBodyOfWater) %>%
  filter(InjuredPropellerInjury=="Y") %>%
  filter(TypeOfBodyOfWater!="") %>%
  summarise(counts = n()) %>%
  filter(counts>=3)


Injuries_BodyofWater_2018 <- ggplot(df_PropellerInjury_2018, aes(x = TypeOfBodyOfWater, y = counts)) +
  geom_bar(fill = "#0073C2FF", stat = "identity") +
  geom_text(aes(label = counts), vjust = -0.3) + 
 labs(y = "Total Injuries", fill="test", x = "", caption = "Figures refer to bodies of water with three or more injuries per year") +
  scale_y_continuous(limits = c(0, 100), breaks = c(0, 20, 40, 60, 80, 100)) + 
  theme(axis.text.x = element_text(angle = 50, hjust = 1)) + theme_minimal() +
  theme(plot.caption = element_text(hjust=-.15))

Injuries_BodyofWater_2018
```

```{r}
df_PropellerInjury_2019 <- Injured_2019 %>%
  group_by(InjuredPropellerInjury, TypeOfBodyOfWater) %>%
  filter(InjuredPropellerInjury=="Y") %>%
  filter(TypeOfBodyOfWater!="") %>%
  summarise(counts = n()) %>%
  filter(counts>=3)


Injuries_BodyofWater_2019 <- ggplot(df_PropellerInjury_2019, aes(x = TypeOfBodyOfWater, y = counts)) +
  geom_bar(fill = "#0073C2FF", stat = "identity") +
  geom_text(aes(label = counts), vjust = -0.3) + 
 labs(y = "", fill="test", x = "") +
  scale_y_continuous(limits = c(0, 100), breaks = c(0, 20, 40, 60, 80, 100)) + 
  theme(axis.text.x = element_text(angle = 50, hjust = 1)) + theme_minimal()

Injuries_BodyofWater_2019
```

```{r}
library("cowplot")
plot_row_injuries_BOW <- plot_grid(Injuries_BodyofWater_2015, Injuries_BodyofWater_2016, Injuries_BodyofWater_2017, Injuries_BodyofWater_2018, Injuries_BodyofWater_2019,
          labels = c("2015", "2016", "2017", "2018", "2019"), hjust = -5.5,
          ncol = 3, nrow = 2)

title_BOW_injuries <- ggdraw() + 
  draw_label(
    "Number of Injuries Associated with a Propeller by Body of Water Type (2015-2019)",
    fontface = 'bold',
    x = 0,
    hjust = 0
  ) +
  theme(
    # add margin on the left of the drawing canvas,
    # so title is aligned with left edge of first plot
    plot.margin = margin(0, 0, 0, 7)
  )

Final_Plot_BOW_Injuries <- plot_grid(
  title_BOW_injuries, plot_row_injuries_BOW,
  ncol = 1,
  # rel_heights values control vertical title margins
  rel_heights = c(0.1, 1)
)

Final_Plot_BOW_Injuries
```

```{r}
df_PropellerInjury_Trend <- Injured_Trend %>%
  group_by(PropellerInjury, TypeOfBodyOfWater) %>%
  filter(PropellerInjury=="Y") %>%
  filter(TypeOfBodyOfWater!="NA") %>%
  summarise(counts = n())  %>%
  filter(counts>=10)

Prop_Injury_BOW_Plot <- ggplot(df_PropellerInjury_Trend, aes(x = TypeOfBodyOfWater, y = counts)) +
  geom_bar(aes(reorder(TypeOfBodyOfWater, counts), counts),fill = "#0073C2FF", stat = "identity") +
  geom_text(aes(label = counts), vjust = -0.3)  +
  scale_y_continuous(limits = c(0, 500), breaks = c(0, 50, 100, 150, 200, 250, 300, 350, 400, 450, 500 )) +
labs(y = "Total Injuries", fill="test", x = "Body of Water (Type)", title = "Number of Injuries Associated with a Propeller by Type of Body of Water (2015-2019)", subtitle = "Figure highlights bodies of water with 10 or more injuries over the past five years") + theme_minimal()

Prop_Injury_BOW_Plot
```

### Now, Let's move onto Coordinate Analysis based on Body of Water Type
```{r}
#Loading necessary packages
library(tidyverse)
library(janitor)
library(readxl)
library(maps)
library(ggdark)
library(ggmap)
```

### Now, Let's Try Mapping the Whole US
```{r}
states <- map_data("state")

Injury_Coordinates_ALL <- Injured_Trend %>%
  
  select(PropellerInjury,State, Latitude, Longitude, TypeOfBodyOfWater) %>%
  filter(!State %in% c("AK", "AM", "PR", "HI")) %>%
  filter(PropellerInjury=="Y") %>%
  filter(TypeOfBodyOfWater=="Bay"|TypeOfBodyOfWater=="River"|TypeOfBodyOfWater=="Lake")

map_borders_all <- subset(states)

ggplot(data=map_borders_all) + 
  geom_polygon(aes(x=long, y=lat, group=group), fill = "palegreen", color="black") + coord_fixed(1.3)
ggplot() +
  geom_polygon(data=map_borders_all, aes(x=long, y=lat, group = group), color="black", fill="#303030", size=1.15) + 
  #Plotting Accident Coordinates Observed
  geom_point(data=Injury_Coordinates_ALL, aes(x=Longitude, y=Latitude, color=TypeOfBodyOfWater)) +
               labs(title="Recreational Boating Injuries in the US Associated with Propeller Strikes (2015-2019)") + 
  dark_mode(theme_minimal()) + 
  scale_size_continuous(breaks=c(1,2,3)) + 
  theme(text=element_text(family="Rockwell", color="white"),
        plot.title=element_text(hjust=0.0, size=12),
        plot.subtitle=element_text(hjust=0.0, size=10),
        axis.title = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        legend.title = element_text(color="white")) 
#+ ggsave("Total Number of Deaths Mapped.png")
```



```{r}
#NOW, let's try to map these states via Google Maps
USbox <- make_bbox(lon=Injury_Coordinates_ALL$Longitude, lat=Injury_Coordinates_ALL$Latitude, f=.1)
US_map <- get_map(location=USbox, maptype = "terrain", source="google")

US_Map_Injuries <-ggmap(US_map) + geom_point(data=Injury_Coordinates_ALL, mapping = aes(x=Longitude, y=Latitude, color=TypeOfBodyOfWater), size=3) +
labs(title="Recreational Boating Injuries in US \nAssociated with Propeller Strikes (2015-2018)") +
   theme(text=element_text(family="Rockwell", color="black"),
        plot.title=element_text(hjust=0.0, size=12),
        plot.subtitle=element_text(hjust=0.0, size=10),
        axis.title = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank()) +
      scale_size_continuous(breaks=c(1,2,3)) +
scale_color_brewer(palette="Dark2")

US_Map_Injuries
```